name: First Workflow
on: workflow_dispatch
jobs: 
  first-job:
    runs-on: ubuntu-latest
    steps: 
      - name: Print greeting
        run: echo "Hello world!"
      - name: Print goodbye
        run: echo "done by Joel"
      - name: Print my two first name in colone
        run: |
            echo "Herve"
            echo "Jules"
